SELECT SVC_TEMPLIT_ID tmplt_id , SVC_TEMPLIT_SEQ tmplt_seq , SVC_TEMPLIT_FIGURE tmplt_figure 
, SVC_TEMPLIT_DES tmplt_des , SVC_TEMPLIT_STTUS tmplt_sttus , SVC_TEMPLIT_USER_ID user_id FROM 
SVC_TEMPLIT_LIST_DTL WHERE SVC_TEMPLIT_USER_ID = 'qwe' ORDER BY SVC_TEMPLIT_SEQ ASC ;
select * from user_info;